borders(afghanistan,china).
borders(afghanistan,iran).
borders(afghanistan,pakistan).
borders(afghanistan,tajikistan).
borders(afghanistan,turkmenistan).
borders(afghanistan,uzbekistan).
borders(albania,greece).
borders(albania,macedonia).
borders(albania,montenegro).
borders(albania,serbia).
borders(albania,atlantic_ocean).
borders(albania,adriatic_sea).
borders(albania,ionian_sea).
borders(algeria,libya).
borders(algeria,mali).
borders(algeria,mauritania).
borders(algeria,morocco).
borders(algeria,niger).
borders(algeria,tunisia).
borders(algeria,western_sahara).
borders(algeria,atlantic_ocean).
borders(algeria,mediterranean_sea).
borders(andorra,france).
borders(andorra,spain).
borders(angola,congo).
borders(angola,namibia).
borders(angola,congo).
borders(angola,zambia).
borders(angola,atlantic_ocean).
borders(antigua_and_barbuda,atlantic_ocean).
borders(antigua_and_barbuda,caribbean_sea).
borders(argentina,bolivia).
borders(argentina,brazil).
borders(argentina,chile).
borders(argentina,paraguay).
borders(argentina,uruguay).
borders(argentina,atlantic_ocean).
borders(argentina,scotia_sea).
borders(armenia,azerbaijan).
borders(armenia,georgia).
borders(armenia,iran).
borders(armenia,turkey).
borders(australia,indian_ocean).
borders(australia,pacific_ocean).
borders(australia,arafura_sea).
borders(australia,coral_sea).
borders(australia,tasman_sea).
borders(australia,timor_sea).
borders(austria,czech_republic).
borders(austria,germany).
borders(austria,hungary).
borders(austria,italy).
borders(austria,liechtenstein).
borders(austria,slovakia).
borders(austria,slovenia).
borders(austria,switzerland).
borders(azerbaijan,armenia).
borders(azerbaijan,georgia).
borders(azerbaijan,iran).
borders(azerbaijan,russia).
borders(azerbaijan,turkey).
borders(azerbaijan,caspian_sea).
borders(bahamas,atlantic_ocean).
borders(bahrain,indian_ocean).
borders(bahrain,persian_gulf).
borders(bangladesh,india).
borders(bangladesh,myanmar).
borders(bangladesh,indian_ocean).
borders(barbados,atlantic_ocean).
borders(belarus,latvia).
borders(belarus,lithuania).
borders(belarus,poland).
borders(belarus,russia).
borders(belarus,ukraine).
borders(belgium,france).
borders(belgium,germany).
borders(belgium,luxembourg).
borders(belgium,netherlands).
borders(belgium,atlantic_ocean).
borders(belgium,north_sea).
borders(belize,guatemala).
borders(belize,mexico).
borders(belize,atlantic_ocean).
borders(belize,caribbean_sea).
borders(benin,burkina_faso).
borders(benin,niger).
borders(benin,nigeria).
borders(benin,togo).
borders(benin,atlantic_ocean).
borders(benin,gulf_of_guinea).
borders(bhutan,china).
borders(bhutan,india).
borders(bolivia,argentina).
borders(bolivia,brazil).
borders(bolivia,chile).
borders(bolivia,paraguay).
borders(bolivia,peru).
borders(bosnia_and_herzegovina,croatia).
borders(bosnia_and_herzegovina,serbia).
borders(bosnia_and_herzegovina,montenegro).
borders(bosnia_and_herzegovina,atlantic_ocean).
borders(bosnia_and_herzegovina,adriatic_sea).
borders(botswana,namibia).
borders(botswana,south_africa).
borders(botswana,zambia).
borders(botswana,zimbabwe).
borders(brazil,argentina).
borders(brazil,bolivia).
borders(brazil,colombia).
borders(brazil,guyana).
borders(brazil,paraguay).
borders(brazil,peru).
borders(brazil,suriname).
borders(brazil,uruguay).
borders(brazil,venezuela).
borders(brazil,atlantic_ocean).
borders(brunei,malaysia).
borders(brunei,pacific_ocean).
borders(brunei,south_china_sea).
borders(bulgaria,greece).
borders(bulgaria,macedonia).
borders(bulgaria,romania).
borders(bulgaria,serbia).
borders(bulgaria,turkey).
borders(bulgaria,atlantic_ocean).
borders(bulgaria,black_sea).
borders(burkina_faso,benin).
borders(burkina_faso,ivory_coast).
borders(burkina_faso,ghana).
borders(burkina_faso,mali).
borders(burkina_faso,niger).
borders(burkina_faso,togo).
borders(burundi,congo).
borders(burundi,rwanda).
borders(burundi,tanzania).
borders(cambodia,laos).
borders(cambodia,thailand).
borders(cambodia,vietnam).
borders(cambodia,pacific_ocean).
borders(cameroon,central_african_republic).
borders(cameroon,chad).
borders(cameroon,congo).
borders(cameroon,equatorial_guinea).
borders(cameroon,gabon).
borders(cameroon,nigeria).
borders(cameroon,atlantic_ocean).
borders(cameroon,gulf_of_guinea).
borders(canada,usa).
borders(canada,arctic_ocean).
borders(canada,atlantic_ocean).
borders(canada,pacific_ocean).
borders(canada,baffin_bay).
borders(canada,beaufort_sea).
borders(canada,hudson_bay).
borders(canada,labrador_sea).
borders(cape_verde,atlantic_ocean).
borders(central_african_republic,cameroon).
borders(central_african_republic,chad).
borders(central_african_republic,congo).
borders(central_african_republic,south_sudan).
borders(central_african_republic,sudan).
borders(chad,cameroon).
borders(chad,central_african_republic).
borders(chad,libya).
borders(chad,niger).
borders(chad,nigeria).
borders(chad,sudan).
borders(chile,argentina).
borders(chile,bolivia).
borders(chile,peru).
borders(chile,pacific_ocean).
borders(china,afghanistan).
borders(china,bhutan).
borders(china,hong_kong).
borders(china,india).
borders(china,kazakhstan).
borders(china,kyrgyzstan).
borders(china,laos).
borders(china,macau).
borders(china,mongolia).
borders(china,myanmar).
borders(china,nepal).
borders(china,north_korea).
borders(china,pakistan).
borders(china,russia).
borders(china,tajikistan).
borders(china,vietnam).
borders(china,pacific_ocean).
borders(china,east_china_sea).
borders(china,south_china_sea).
borders(china,yellow_sea).
borders(colombia,brazil).
borders(colombia,ecuador).
borders(colombia,panama).
borders(colombia,peru).
borders(colombia,venezuela).
borders(colombia,pacific_ocean).
borders(colombia,atlantic_ocean).
borders(colombia,caribbean_sea).
borders(comoros,indian_ocean).
borders(congo,angola).
borders(congo,burundi).
borders(congo,central_african_republic).
borders(congo,congo).
borders(congo,rwanda).
borders(congo,south_sudan).
borders(congo,tanzania).
borders(congo,uganda).
borders(congo,zambia).
borders(congo,atlantic_ocean).
borders(costa_rica,nicaragua).
borders(costa_rica,panama).
borders(costa_rica,atlantic_ocean).
borders(costa_rica,pacific_ocean).
borders(costa_rica,caribbean_sea).
borders(cote_divoire,burkina_faso).
borders(cote_divoire,ghana).
borders(cote_divoire,guinea).
borders(cote_divoire,liberia).
borders(cote_divoire,mali).
borders(cote_divoire,atlantic_ocean).
borders(croatia,bosnia_and_herzegovina).
borders(croatia,hungary).
borders(croatia,serbia).
borders(croatia,montenegro).
borders(croatia,slovenia).
borders(croatia,atlantic_ocean).
borders(croatia,adriatic_sea).
borders(cuba,atlantic_ocean).
borders(cuba,caribbean_sea).
borders(cuba,gulf_of_mexico).
borders(cyprus,akrotiri).
borders(cyprus,dhekelia).
borders(cyprus,atlantic_ocean).
borders(cyprus,mediterranean_sea).
borders(czech_republic,austria).
borders(czech_republic,germany).
borders(czech_republic,poland).
borders(czech_republic,slovakia).
borders(denmark,germany).
borders(denmark,atlantic_ocean).
borders(denmark,baltic_sea).
borders(denmark,north_sea).
borders(djibouti,eritrea).
borders(djibouti,ethiopia).
borders(djibouti,somalia).
borders(djibouti,indian_ocean).
borders(djibouti,red_sea).
borders(djibouti,gulf_of_aden).
borders(dominica,atlantic_ocean).
borders(dominica,caribbean_sea).
borders(dominican_republic,haiti).
borders(dominican_republic,atlantic_ocean).
borders(dominican_republic,caribbean_sea).
borders(ecuador,colombia).
borders(ecuador,peru).
borders(ecuador,pacific_ocean).
borders(egypt,israel).
borders(egypt,libya).
borders(egypt,sudan).
borders(egypt,atlantic_ocean).
borders(egypt,indian_ocean).
borders(egypt,mediterranean_sea).
borders(egypt,red_sea).
borders(el_salvador,guatemala).
borders(el_salvador,honduras).
borders(el_salvador,pacific_ocean).
borders(equatorial_guinea,cameroon).
borders(equatorial_guinea,gabon).
borders(equatorial_guinea,atlantic_ocean).
borders(equatorial_guinea,gulf_of_guinea).
borders(eritrea,djibouti).
borders(eritrea,ethiopia).
borders(eritrea,sudan).
borders(eritrea,indian_ocean).
borders(eritrea,red_sea).
borders(estonia,latvia).
borders(estonia,russia).
borders(estonia,atlantic_ocean).
borders(estonia,baltic_sea).
borders(estonia,gulf_of_finland).
borders(ethiopia,djibouti).
borders(ethiopia,eritrea).
borders(ethiopia,kenya).
borders(ethiopia,somalia).
borders(ethiopia,south_sudan).
borders(ethiopia,sudan).
borders(fiji,pacific_ocean).
borders(finland,norway).
borders(finland,russia).
borders(finland,sweden).
borders(finland,atlantic_ocean).
borders(finland,baltic_sea).
borders(finland,gulf_of_finland).
borders(france,andorra).
borders(france,belgium).
borders(france,germany).
borders(france,italy).
borders(france,luxembourg).
borders(france,monaco).
borders(france,spain).
borders(france,switzerland).
borders(france,atlantic_ocean).
borders(france,bay_of_biscay).
borders(france,english_channel).
borders(france,mediterranean_sea).
borders(france,north_sea).
borders(gabon,cameroon).
borders(gabon,congo).
borders(gabon,equatorial_guinea).
borders(gabon,atlantic_ocean).
borders(gabon,gulf_of_guinea).
borders(gambia,senegal).
borders(gambia,atlantic_ocean).
borders(georgia,armenia).
borders(georgia,azerbaijan).
borders(georgia,russia).
borders(georgia,turkey).
borders(georgia,atlantic_ocean).
borders(georgia,black_sea).
borders(germany,austria).
borders(germany,belgium).
borders(germany,czech_republic).
borders(germany,denmark).
borders(germany,france).
borders(germany,luxembourg).
borders(germany,netherlands).
borders(germany,poland).
borders(germany,switzerland).
borders(germany,atlantic_ocean).
borders(germany,north_sea).
borders(germany,baltic_sea).
borders(ghana,burkina_faso).
borders(ghana,ivory_coast).
borders(ghana,togo).
borders(ghana,atlantic_ocean).
borders(ghana,gulf_of_guinea).
borders(gibraltar,spain).
borders(gibraltar,atlantic_ocean).
borders(gibraltar,mediterranean_sea).
borders(greece,albania).
borders(greece,bulgaria).
borders(greece,macedonia).
borders(greece,turkey).
borders(greece,atlantic_ocean).
borders(greece,aegean_sea).
borders(greece,ionian_sea).
borders(greece,mediterranean_sea).
borders(grenada,caribbean_sea).
borders(guatemala,belize).
borders(guatemala,el_salvador).
borders(guatemala,honduras).
borders(guatemala,mexico).
borders(guatemala,atlantic_ocean).
borders(guatemala,pacific_ocean).
borders(guatemala,caribbean_sea).
borders(guinea,ivory_coast).
borders(guinea,guinea-bissau).
borders(guinea,liberia).
borders(guinea,mali).
borders(guinea,senegal).
borders(guinea,sierra_leone).
borders(guinea,atlantic_ocean).
borders(guinea-bissau,guinea).
borders(guinea-bissau,senegal).
borders(guinea-bissau,atlantic_ocean).
borders(guyana,brazil).
borders(guyana,suriname).
borders(guyana,venezuela).
borders(guyana,atlantic_ocean).
borders(haiti,dominican_republic).
borders(haiti,atlantic_ocean).
borders(haiti,caribbean_sea).
borders(honduras,el_salvador).
borders(honduras,guatemala).
borders(honduras,nicaragua).
borders(honduras,atlantic_ocean).
borders(honduras,pacific_ocean).
borders(honduras,caribbean_sea).
borders(hungary,austria).
borders(hungary,croatia).
borders(hungary,romania).
borders(hungary,serbia).
borders(hungary,slovakia).
borders(hungary,slovenia).
borders(hungary,ukraine).
borders(iceland,atlantic_ocean).
borders(iceland,arctic_ocean).
borders(india,bangladesh).
borders(india,bhutan).
borders(india,china).
borders(india,myanmar).
borders(india,nepal).
borders(india,pakistan).
borders(india,indian_ocean).
borders(india,arabian_sea).
borders(india,bay_of_bengal).
borders(indonesia,east_timor).
borders(indonesia,malaysia).
borders(indonesia,papua_new_guinea).
borders(indonesia,indian_ocean).
borders(indonesia,pacific_ocean).
borders(indonesia,arafura_sea).
borders(indonesia,banda_sea).
borders(indonesia,celebes_sea).
borders(indonesia,java_sea).
borders(indonesia,molucca_sea).
borders(indonesia,timor_sea).
borders(iran,afghanistan).
borders(iran,armenia).
borders(iran,azerbaijan).
borders(iran,iraq).
borders(iran,pakistan).
borders(iran,turkey).
borders(iran,turkmenistan).
borders(iran,caspian_sea).
borders(iran,indian_ocean).
borders(iran,gulf_of_oman).
borders(iran,persian_gulf).
borders(iraq,iran).
borders(iraq,jordan).
borders(iraq,kuwait).
borders(iraq,saudi_arabia).
borders(iraq,syria).
borders(iraq,turkey).
borders(iraq,indian_ocean).
borders(iraq,persian_gulf).
borders(ireland,uk).
borders(ireland,atlantic_ocean).
borders(ireland,irish_sea).
borders(israel,egypt).
borders(israel,jordan).
borders(israel,lebanon).
borders(israel,syria).
borders(israel,atlantic_ocean).
borders(israel,mediterranean_sea).
borders(italy,austria).
borders(italy,france).
borders(italy,san_marino).
borders(italy,slovenia).
borders(italy,switzerland).
borders(italy,vatican_city).
borders(italy,atlantic_ocean).
borders(italy,mediterranean_sea).
borders(jamaica,atlantic_ocean).
borders(jamaica,caribbean_sea).
borders(japan,pacific_ocean).
borders(japan,east_china_sea).
borders(japan,sea_of_japan).
borders(japan,sea_of_okhotsk).
borders(jordan,iraq).
borders(jordan,israel).
borders(jordan,saudi_arabia).
borders(jordan,syria).
borders(jordan,indian_ocean).
borders(jordan,gulf_of_aqaba).
borders(kazakhstan,china).
borders(kazakhstan,kyrgyzstan).
borders(kazakhstan,russia).
borders(kazakhstan,turkmenistan).
borders(kazakhstan,uzbekistan).
borders(kazakhstan,caspian_sea).
borders(kenya,ethiopia).
borders(kenya,somalia).
borders(kenya,south_sudan).
borders(kenya,tanzania).
borders(kenya,uganda).
borders(kenya,indian_ocean).
borders(kiribati,pacific_ocean).
borders(kuwait,iraq).
borders(kuwait,saudi_arabia).
borders(kuwait,indian_ocean).
borders(kuwait,persian_gulf).
borders(kyrgyzstan,china).
borders(kyrgyzstan,kazakhstan).
borders(kyrgyzstan,tajikistan).
borders(kyrgyzstan,uzbekistan).
borders(laos,cambodia).
borders(laos,china).
borders(laos,myanmar).
borders(laos,thailand).
borders(laos,vietnam).
borders(latvia,belarus).
borders(latvia,estonia).
borders(latvia,lithuania).
borders(latvia,russia).
borders(latvia,atlantic_ocean).
borders(latvia,baltic_sea).
borders(lebanon,syria).
borders(lebanon,israel).
borders(lebanon,atlantic_ocean).
borders(lebanon,mediterranean_sea).
borders(lesotho,south_africa).
borders(liberia,ivory_coast).
borders(liberia,guinea).
borders(liberia,sierra_leone).
borders(liberia,atlantic_ocean).
borders(libya,algeria).
borders(libya,chad).
borders(libya,egypt).
borders(libya,niger).
borders(libya,sudan).
borders(libya,tunisia).
borders(libya,atlantic_ocean).
borders(libya,mediterranean_sea).
borders(liechtenstein,austria).
borders(liechtenstein,switzerland).
borders(lithuania,belarus).
borders(lithuania,latvia).
borders(lithuania,poland).
borders(lithuania,russia).
borders(lithuania,atlantic_ocean).
borders(lithuania,baltic_sea).
borders(luxembourg,belgium).
borders(luxembourg,france).
borders(luxembourg,germany).
borders(macedonia,albania).
borders(macedonia,bulgaria).
borders(macedonia,greece).
borders(macedonia,serbia).
borders(madagascar,indian_ocean).
borders(madagascar,mozambique_channel).
borders(malawi,mozambique).
borders(malawi,tanzania).
borders(malawi,zambia).
borders(malaysia,brunei).
borders(malaysia,indonesia).
borders(malaysia,singapore).
borders(malaysia,thailand).
borders(malaysia,indian_ocean).
borders(malaysia,pacific_ocean).
borders(malaysia,south_china_sea).
borders(maldives,indian_ocean).
borders(mali,algeria).
borders(mali,burkina_faso).
borders(mali,ivory_coast).
borders(mali,guinea).
borders(mali,mauritania).
borders(mali,niger).
borders(mali,senegal).
borders(malta,atlantic_ocean).
borders(malta,mediterranean_sea).
borders(marshall_islands,pacific_ocean).
borders(martinique,caribbean_sea).
borders(mauritania,algeria).
borders(mauritania,mali).
borders(mauritania,senegal).
borders(mauritania,western_sahara).
borders(mauritania,atlantic_ocean).
borders(mexico,belize).
borders(mexico,guatemala).
borders(mexico,usa).
borders(mexico,atlantic_ocean).
borders(mexico,pacific_ocean).
borders(mexico,gulf_of_mexico).
borders(mexico,caribbean_sea).
borders(micronesia,pacific_ocean).
borders(moldova,romania).
borders(moldova,ukraine).
borders(monaco,france).
borders(monaco,atlantic_ocean).
borders(monaco,mediterranean_sea).
borders(mongolia,china).
borders(mongolia,russia).
borders(montenegro,albania).
borders(montenegro,bosnia_herzegovina).
borders(montenegro,croatia).
borders(montenegro,serbia).
borders(montenegro,atlantic_ocean).
borders(montenegro,mediterranean_sea).
borders(morocco,algeria).
borders(morocco,ceuta).
borders(morocco,melilla).
borders(morocco,penon_de_velez_de_la_gomera).
borders(morocco,western_sahara).
borders(morocco,atlantic_ocean).
borders(morocco,mediterranean_sea).
borders(mozambique,malawi).
borders(mozambique,south_africa).
borders(mozambique,swaziland).
borders(mozambique,tanzania).
borders(mozambique,zambia).
borders(mozambique,zimbabwe).
borders(mozambique,indian_ocean).
borders(myanmar,bangladesh).
borders(myanmar,china).
borders(myanmar,india).
borders(myanmar,laos).
borders(myanmar,thailand).
borders(myanmar,indian_ocean).
borders(myanmar,andaman_sea).
borders(namibia,angola).
borders(namibia,botswana).
borders(namibia,south_africa).
borders(namibia,zambia).
borders(namibia,atlantic_ocean).
borders(nauru,pacific_ocean).
borders(nepal,china).
borders(nepal,india).
borders(netherlands,belgium).
borders(netherlands,germany).
borders(netherlands,atlantic_ocean).
borders(netherlands,north_sea).
borders(new_zealand,pacific_ocean).
borders(nicaragua,costa_rica).
borders(nicaragua,honduras).
borders(nicaragua,atlantic_ocean).
borders(nicaragua,pacific_ocean).
borders(nicaragua,caribbean_sea).
borders(niger,algeria).
borders(niger,benin).
borders(niger,burkina_faso).
borders(niger,chad).
borders(niger,libya).
borders(niger,mali).
borders(niger,nigeria).
borders(nigeria,benin).
borders(nigeria,cameroon).
borders(nigeria,chad).
borders(nigeria,niger).
borders(nigeria,atlantic_ocean).
borders(nigeria,gulf_of_guinea).
borders(north_korea,china).
borders(north_korea,republic_of_korea).
borders(north_korea,russia).
borders(north_korea,pacific_ocean).
borders(north_korea,korea_bay).
borders(north_korea,sea_of_japan).
borders(north_korea,yellow_sea).
borders(norway,finland).
borders(norway,russia).
borders(norway,sweden).
borders(norway,arctic_ocean).
borders(norway,atlantic_ocean).
borders(oman,saudi_arabia).
borders(oman,united_arab_emirates).
borders(oman,yemen).
borders(oman,indian_ocean).
borders(pakistan,afghanistan).
borders(pakistan,china).
borders(pakistan,india).
borders(pakistan,iran).
borders(pakistan,indian_ocean).
borders(palau,pacific_ocean).
borders(panama,colombia).
borders(panama,costa_rica).
borders(panama,atlantic_ocean).
borders(panama,caribbean_sea).
borders(panama,pacific_ocean).
borders(papua_new_guinea,indonesia).
borders(papua_new_guinea,pacific_ocean).
borders(paraguay,argentina).
borders(paraguay,bolivia).
borders(paraguay,brazil).
borders(peru,bolivia).
borders(peru,brazil).
borders(peru,chile).
borders(peru,colombia).
borders(peru,ecuador).
borders(peru,pacific_ocean).
borders(philippines,pacific_ocean).
borders(poland,belarus).
borders(poland,czech_republic).
borders(poland,germany).
borders(poland,lithuania).
borders(poland,russia).
borders(poland,slovakia).
borders(poland,ukraine).
borders(poland,atlantic_ocean).
borders(poland,baltic_sea).
borders(portugal,spain).
borders(portugal,atlantic_ocean).
borders(qatar,saudi_arabia).
borders(qatar,indian_ocean).
borders(qatar,persian_gulf).
borders(romania,bulgaria).
borders(romania,hungary).
borders(romania,moldova).
borders(romania,serbia).
borders(romania,ukraine).
borders(romania,atlantic_ocean).
borders(romania,black_sea).
borders(russia,azerbaijan).
borders(russia,belarus).
borders(russia,china).
borders(russia,estonia).
borders(russia,finland).
borders(russia,georgia).
borders(russia,kazakhstan).
borders(russia,latvia).
borders(russia,lithuania).
borders(russia,mongolia).
borders(russia,north_korea).
borders(russia,norway).
borders(russia,poland).
borders(russia,ukraine).
borders(russia,arctic_ocean).
borders(russia,atlantic_ocean).
borders(russia,baltic_sea).
borders(russia,black_sea).
borders(russia,caspian_sea).
borders(russia,pacific_ocean).
borders(rwanda,burundi).
borders(rwanda,congo).
borders(rwanda,tanzania).
borders(rwanda,uganda).
borders(saint_kitts_and_nevis,atlantic_ocean).
borders(saint_kitts_and_nevis,caribbean_sea).
borders(saint_lucia,atlantic_ocean).
borders(saint_lucia,caribbean_sea).
borders(saint_vincent_and_the_grenadines,atlantic_ocean).
borders(saint_vincent_and_the_grenadines,caribbean_sea).
borders(samoa,pacific_ocean).
borders(san_marino,italy).
borders(sao_tome_and_principe,atlantic_ocean).
borders(sao_tome_and_principe,gulf_of_guinea).
borders(saudi_arabia,iraq).
borders(saudi_arabia,jordan).
borders(saudi_arabia,kuwait).
borders(saudi_arabia,oman).
borders(saudi_arabia,qatar).
borders(saudi_arabia,united_arab_emirates).
borders(saudi_arabia,yemen).
borders(saudi_arabia,indian_ocean).
borders(saudi_arabia,red_sea).
borders(saudi_arabia,persian_gulf).
borders(senegal,the_gambia).
borders(senegal,mali).
borders(senegal,mauritania).
borders(senegal,guinea).
borders(senegal,guinea_bissau).
borders(senegal,atlantic_ocean).
borders(serbia,albania).
borders(serbia,bosnia).
borders(serbia,bulgaria).
borders(serbia,croatia).
borders(serbia,hungary).
borders(serbia,macedonia).
borders(serbia,montenegro).
borders(serbia,romania).
borders(seychelles,indian_ocean).
borders(sierra_leone,guinea).
borders(sierra_leone,liberia).
borders(sierra_leone,atlantic_ocean).
borders(singapore,malaysia).
borders(singapore,pacific_ocean).
borders(singapore,indian_ocean).
borders(singapore,south_china_sea).
borders(slovakia,austria).
borders(slovakia,czech_republic).
borders(slovakia,hungary).
borders(slovakia,poland).
borders(slovakia,ukraine).
borders(slovenia,austria).
borders(slovenia,croatia).
borders(slovenia,hungary).
borders(slovenia,italy).
borders(slovenia,atlantic_ocean).
borders(slovenia,adriatic_sea).
borders(solomon_islands,pacific_ocean).
borders(somalia,djibouti).
borders(somalia,ethiopia).
borders(somalia,kenya).
borders(somalia,indian_ocean).
borders(somalia,gulf_of_aden).
borders(south_africa,botswana).
borders(south_africa,lesotho).
borders(south_africa,mozambique).
borders(south_africa,namibia).
borders(south_africa,swaziland).
borders(south_africa,zimbabwe).
borders(south_africa,atlantic_ocean).
borders(south_africa,indian_ocean).
borders(south_korea,north_korea).
borders(south_korea,pacific_ocean).
borders(south_korea,sea_of_japan).
borders(south_korea,yellow_sea).
borders(spain,andorra).
borders(spain,france).
borders(spain,portugal).
borders(spain,gibraltar).
borders(spain,atlantic_ocean).
borders(spain,mediterranean_sea).
borders(sri_lanka,indian_ocean).
borders(sudan,central_african_republic).
borders(sudan,chad).
borders(sudan,egypt).
borders(sudan,eritrea).
borders(sudan,ethiopia).
borders(sudan,libya).
borders(sudan,south_sudan).
borders(sudan,indian_ocean).
borders(sudan,red_sea).
borders(suriname,brazil).
borders(suriname,guyana).
borders(suriname,atlantic_ocean).
borders(swaziland,mozambique).
borders(swaziland,south_africa).
borders(sweden,finland).
borders(sweden,norway).
borders(sweden,atlantic_ocean).
borders(sweden,baltic_sea).
borders(switzerland,austria).
borders(switzerland,france).
borders(switzerland,germany).
borders(switzerland,italy).
borders(switzerland,liechtenstein).
borders(syria,iraq).
borders(syria,israel).
borders(syria,jordan).
borders(syria,lebanon).
borders(syria,turkey).
borders(syria,atlantic_ocean).
borders(syria,mediterranean_sea).
borders(taiwan,pacific_ocean).
borders(taiwan,east_china_sea).
borders(taiwan,south_china_sea).
borders(tajikistan,afghanistan).
borders(tajikistan,china).
borders(tajikistan,kyrgyzstan).
borders(tajikistan,uzbekistan).
borders(tanzania,burundi).
borders(tanzania,congo).
borders(tanzania,kenya).
borders(tanzania,malawi).
borders(tanzania,mozambique).
borders(tanzania,rwanda).
borders(tanzania,uganda).
borders(tanzania,zambia).
borders(tanzania,indian_ocean).
borders(thailand,cambodia).
borders(thailand,laos).
borders(thailand,malaysia).
borders(thailand,myanmar).
borders(thailand,indian_ocean).
borders(thailand,pacific_ocean).
borders(thailand,south_china_sea).
borders(togo,benin).
borders(togo,burkina_faso).
borders(togo,ghana).
borders(togo,atlantic_ocean).
borders(togo,gulf_of_guinea).
borders(tonga,pacific_ocean).
borders(trinidad_and_tobago,atlantic_ocean).
borders(trinidad_and_tobago,caribbean_sea).
borders(tunisia,algeria).
borders(tunisia,libya).
borders(tunisia,atlantic_ocean).
borders(tunisia,mediterranean_sea).
borders(turkey,armenia).
borders(turkey,azerbaijan).
borders(turkey,bulgaria).
borders(turkey,georgia).
borders(turkey,greece).
borders(turkey,iran).
borders(turkey,iraq).
borders(turkey,syria).
borders(turkey,atlantic_ocean).
borders(turkey,mediterranean_sea).
borders(turkey,aegean_sea).
borders(turkey,marmara_sea).
borders(turkey,black_sea).
borders(turkmenistan,afghanistan).
borders(turkmenistan,iran).
borders(turkmenistan,kazakhstan).
borders(turkmenistan,uzbekistan).
borders(turkmenistan,caspian_sea).
borders(tuvalu,pacific_ocean).
borders(uganda,congo).
borders(uganda,kenya).
borders(uganda,rwanda).
borders(uganda,south_sudan).
borders(uganda,tanzania).
borders(ukraine,belarus).
borders(ukraine,hungary).
borders(ukraine,moldova).
borders(ukraine,poland).
borders(ukraine,romania).
borders(ukraine,russia).
borders(ukraine,slovakia).
borders(ukraine,atlantic_ocean).
borders(ukraine,black_sea).
borders(united_arab_emirates,oman).
borders(united_arab_emirates,saudi_arabia).
borders(united_arab_emirates,indian_ocean).
borders(united_arab_emirates,persian_gulf).
borders(uk,ireland).
borders(uk,atlantic_ocean).
borders(usa,canada).
borders(usa,mexico).
borders(usa,arctic_ocean).
borders(usa,atlantic_ocean).
borders(usa,pacific_ocean).
borders(usa,gulf_of_mexico).
borders(uruguay,argentina).
borders(uruguay,brazil).
borders(uruguay,atlantic_ocean).
borders(uzbekistan,afghanistan).
borders(uzbekistan,kazakhstan).
borders(uzbekistan,kyrgyzstan).
borders(uzbekistan,tajikistan).
borders(uzbekistan,turkmenistan).
borders(vanuatu,pacific_ocean).
borders(venezuela,brazil).
borders(venezuela,colombia).
borders(venezuela,guyana).
borders(venezuela,atlantic_ocean).
borders(venezuela,caribbean_sea).
borders(vietnam,cambodia).
borders(vietnam,china).
borders(vietnam,laos).
borders(vietnam,pacific_ocean).
borders(vietnam,south_china_sea).
borders(yemen,oman).
borders(yemen,saudi_arabia).
borders(yemen,indian_ocean).
borders(yemen,arabian_sea).
borders(yemen,gulf_of_aden).
borders(yemen,red_sea).
borders(zambia,angola).
borders(zambia,botswana).
borders(zambia,congo).
borders(zambia,malawi).
borders(zambia,mozambique).
borders(zambia,namibia).
borders(zambia,tanzania).
borders(zambia,zimbabwe).
borders(zimbabwe,botswana).
borders(zimbabwe,mozambique).
borders(zimbabwe,south_africa).
borders(zimbabwe,zambia).

