river(amazon,[atlantic_ocean,brazil,peru,bolivia,colombia,ecuador,venezuela,guyana]).
river(amu_darya,[aral_sea,uzbekistan,turkmenistan,tajikistan,afghanistan]).
river(amur,[sea_of_okhotsk,russia,china,mongolia]).
river(anadyr,[gulf_of_anadyr,russia]).
river(araguaia,[tocantins,brazil]).
river(aras,[kura,turkey,armenia,azerbaijan,iran]).
river(arkansas,[mississippi,usa]).
river(aruwimi,[congo_river,congo]).
river(athabasca,[mackenzie,canada]).
river(ayeyarwady,[andaman_sea,myanmar]).
river(belaya,[kama,russia]).
river(beni,[madeira,bolivia]).
river(benue,[niger,cameroon,nigeria]).
river(bermejo,[paraguay,argentina,bolivia]).
river(blue_nile,[nile,ethiopia,sudan]).
river(brahmaputra,[ganges,india,china,nepal,bangladesh,india,bhutan]).
river(brazos,[gulf_of_mexico,usa]).
river(canadian,[arkansas,usa]).
river(cauca,[magdalena,colombia]).
river(chenab,[indus,india,pakistan]).
river(chindwin,[ayeyarwady,myanmar]).
river(chu_river,[none,kyrgyzstan,kazakhstan]).
river(churchill,[hudson_bay,canada]).
river(cimarron,[arkansas,usa]).
river(colorado,[gulf_of_california,gulf_of_mexico,usa,mexico]).
river(columbia,[pacific_ocean,usa,canada]).
river(congo,[atlantic_ocean,congo,central_african_republic,angola,tanzania,cameroon,zambia,burundi,rwanda]).
river(cooper,[lake_eyre,australia]).
river(cumberland,[mississippi,usa]).
river(danube,[black_sea,romania,hungary,austria,serbia,germany,slovakia,bulgaria,croatia]).
river(daugava,[gulf_of_riga,latvia,belarus,russia]).
river(desna,[dnieper,russia,belarus,ukraine]).
river(dnieper,[black_sea,russia,belarus,ukraine]).
river(dniester,[black_sea,ukraine,moldova]).
river(don,[sea_of_azov,russia,ukraine]).
river(douro,[atlantic_ocean,spain,portugal]).
river(draa,[atlantic_ocean,morocco]).
river(dvina,[white_sea,russia]).
river(elbe,[north_sea,germany,czech_republic]).
river(essequibo,[atlantic_ocean,guyana]).
river(euphrates,[persian_gulf,iraq,syria,turkey]).
river(fly,[gulf_of_papua,papua_new_guinea,indonesia]).
river(fraser,[pacific_ocean,canada]).
river(gambia,[atlantic_ocean,the_gambia,senegal,guinea]).
river(ganges,[indian_ocean,india,bangladesh,nepal,china]).
river(ghaghara,[ganges,india,nepal,china]).
river(gila,[colorado,usa]).
river(godavari,[bay_of_bengal,india]).
river(grande,[parana,brazil]).
river(green,[colorado,usa]).
river(guapore,[mamore,brazil,bolivia]).
river(guaviare,[orinoco,colombia]).
river(han,[yangtze,china]).
river(helmand,[hamun-i-helmand,afghanistan,iran]).
river(huai,[none,china]).
river(huallaga,[maranon,peru]).
river(putumayo,[amazon,brazil,peru,colombia,ecuador]).
river(iguacu,[parana,brazil,argentina]).
river(ili,[lake_balkhash,china,kazakhstan]).
river(indigirka,[east_siberian_sea,russia]).
river(indus,[arabian_sea,pakistan,india,china]).
river(iriri,[xingu,brazil]).
river(ishim,[irtysh,kazakhstan,russia]).
river(james-dakotas,[missouri,usa]).
river(james-virginia,[hampton-oads,usa]).
river(japura,[amazon,brazil,colombia]).
river(jialing,[yangtze,china]).
river(jubba,[indian_ocean,ethiopia,somalia]).
river(jurua,[amazon,peru,brazil]).
river(juruena,[tapajos,brazil]).
river(kama,[volga,russia]).
river(kapuas,[south_china_sea,indonesia]).
river(kasai,[congo,angola,congo]).
river(khatanga,[laptev_sea,russia]).
river(khoper,[don,russia]).
river(kizilirmak,[black_sea,turkey]).
river(kolyma,[east_siberian_sea,russia]).
river(krishna,[bay_of_bengal,india]).
river(kuskokwim,[bering_sea,usa]).
river(kwango,[kasai,angola,congo]).
river(lena,[laptev_sea,russia]).
river(lerma,[pacific_ocean,mexico]).
river(liao,[bohai_sea,china]).
river(liard,[mackenzie,canada]).
river(limpopo,[indian_ocean,mozambique,zimbabwe,south_africa,botswana]).
river(loire,[atlantic_ocean,france]).
river(lomami,[congo,congo]).
river(lower_tunguska,[yenisei,russia]).
river(mackenzie,[beaufort_sea,canada]).
river(madeira,[amazon,brazil,bolivia,peru]).
river(madre_de_dios,[beni,peru,bolivia]).
river(magdalena,[caribbean,colombia]).
river(maranon,[amazon,peru]).
river(mekong,[south_china_sea,china,myanmar,laos,thailand,cambodia,vietnam]).
river(milk,[missouri,usa,canada]).
river(minho,[atlantic_ocean,spain,portugal]).
river(mississippi,[gulf_of_mexico,usa,canada]).
river(mtkvari,[caspian_sea,azerbaijan,georgia,armenia,turkey,iran]).
river(murray,[southern_ocean,australia]).
river(murrumbidgee_river,[murray_river,australia]).
river(narmada,[arabian_sea,india]).
river(negro,[amazon,brazil,venezuela,colombia]).
river(nelson,[hudson_bay,canada,usa]).
river(nen,[songhua,china]).
river(niger,[gulf_of_guinea,nigeria,mali,niger,algeria,guinea,cameroon,burkina_faso,cote_divoire,benin,chad]).
river(nile,[mediterranean,ethiopia,eritrea,sudan,uganda,tanzania,kenya,rwanda,burundi,egypt,congo,south_sudan]).
river(north_saskatchewan,[saskatchewan,canada]).
river(ob,[gulf_of_ob,russia,kazakhstan,china,mongolia]).
river(ohio,[mississippi,usa]).
river(oka,[volga,russia]).
river(okavango,[okavango_delta,namibia,angola,botswana]).
river(olenyok,[laptev_sea,russia]).
river(olyokma,[lena,russia]).
river(orange,[atlantic_ocean,south_africa,namibia,botswana,lesotho]).
river(orinoco,[atlantic_ocean,venezuela,colombia,guyana]).
river(ottawa,[saint_lawrence,canada]).
river(paraguay,[parana,brazil,paraguay,bolivia,argentina]).
river(paraiba_do_sul,[atlantic_ocean,brazil]).
river(parana,[rio_de_la_plata,brazil,argentina,paraguay,bolivia,uruguay]).
river(paranaiba,[parana,brazil]).
river(pearl,[south_china_sea,china,vietnam]).
river(pechora,[barents_sea,russia]).
river(pecos,[rio_grande,usa]).
river(pilcomayo,[paraguay,paraguay,argentina,bolivia]).
river(platte,[missouri,usa]).
river(purus,[amazon,brazil,peru]).
river(red,[mississippi,usa]).
river(red_asia,[gulf_of_tonkin,china,vietnam]).
river(rhine,[north_sea,germany,france,switzerland,netherlands,austria,liechtenstein,italy,belgium,luxembourg]).
river(rio_grande,[gulf_of_mexico,usa,mexico]).
river(rio_grande,[ichilo,bolivia]).
river(saint_lawrence,[gulf_of_saint_lawrence,canada,usa]).
river(salado,[parana,argentina]).
river(salween,[andaman_sea,china,myanmar,thailand]).
river(sankuru,[kasai,congo]).
river(sao_francisco,[atlantic_ocean,brazil]).
river(senegal,[atlantic_ocean,guinea,senegal,mali,mauritania]).
river(sepik,[pacific_ocean,papua_new_guinea,indonesia]).
river(severn,[uk]).
river(seversky_donets,[don,russia,ukraine]).
river(shatt_al-arab,[persian_gulf,iraq,turkey,syria]).
river(shire,[zambezi,mozambique,malawi]).
river(snake,[columbia,usa]).
river(songhua,[amur,china]).
river(stony_tunguska,[yenisei,russia]).
river(sutlej,[chenab,china,india,pakistan]).
river(syr_darya,[aral_sea,kazakhstan,kyrgyzstan,uzbekistan,tajikistan]).
river(tapajos,[amazon,brazil]).
river(tarim,[lop_nur,china]).
river(tejo,[atlantic_ocean,spain,portugal]).
river(tennessee,[ohio,usa]).
river(thames,[uk]).
river(tiete,[parana,brazil]).
river(tigris,[shatt_al-arab,turkey,iraq,syria]).
river(tobol,[irtysh,kazakhstan,russia]).
river(tocantins,[atlantic_ocean,amazon,brazil]).
river(ubangi,[congo,congo,central_african_republic]).
river(upper_mississippi,[mississippi,usa]).
river(upper_ob,[ob,russia]).
river(upper_yenisei,[yenisei,russia,mongolia]).
river(ural,[caspian_sea,russia,kazakhstan]).
river(uruguay,[atlantic_ocean,uruguay,argentina,brazil]).
river(vaal,[orange,south_africa]).
river(vilyuy,[lena,russia]).
river(vistula,[baltic_sea,poland]).
river(vitim,[lena,russia]).
river(volga,[caspian_sea,russia]).
river(volta,[gulf_of_guinea,ghana,burkina_faso,togo,cote_divoire,benin]).
river(vyatka,[kama,russia]).
river(vychegda,[northern_dvina,russia]).
river(warburton,[lake_eyre,australia]).
river(white,[mississippi,usa]).
river(wu,[yangtze_river,china]).
river(xingu,[amazon,brazil]).
river(yalong,[yangtze,china]).
river(yamuna,[ganges,india]).
river(yangtze,[pacific_ocean,china]).
river(yellow_river,[bohai_sea,china]).
river(yellowstone,[missouri,usa]).
river(yenisei,[kara_sea,russia,mongolia]).
river(yukon,[bering_sea,usa,canada]).
river(zambezi,[mozambique_channel,zambia,angola,zimbabwe,mozambique,malawi,tanzania,namibia,botswana]).
river(zeya,[amur,russia]).

ocean(atlantic_ocean).
ocean(indian_ocean).
ocean(pacific_ocean).
ocean(arctic_ocean).
ocean(antarctic_ocean).
